# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="DANKOGAI"
MODULE_VERSION="${PV}"


inherit perl-module

DESCRIPTION="URI::Escape::XS - Drop-In replacement for URI::Escape"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="x86 amd64"
IUSE=""

