# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="NWELLNHOF"
MODULE_VERSION="0.240100"


inherit perl-module

DESCRIPTION="Interface to the CommonMark C library"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="x86 amd64"
IUSE=""

DEPEND="dev-lang/perl
	>=dev-libs/cmark-0.21.0
"

src_prepare() {
    epatch "${FILESDIR}/remove_dep.patch"
}
