# Copyright 1999-2014 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.5

EAPI=5

MODULE_AUTHOR="TOKUHIROM"
MODULE_VERSION="0.10"


inherit perl-module

DESCRIPTION="Module::Build meets plugins"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="x86 amd64"
IUSE=""

DEPEND="dev-perl/Class-Accessor-Lite
	dev-perl/Data-OptList
	dev-perl/Class-Method-Modifiers
	dev-perl/Test-SharedFork
	dev-perl/Module-Build
	dev-lang/perl"
